@CulinaryBlog.API_HostAddress = http://localhost:5018

POST {{CulinaryBlog.API_HostAddress}}/api/Auth/register
Content-Type: application/json

{
	"email": "test@example.com",
	"password": "Password123!",
	"fullName": "Test User"
}
